### ISSUE TITLE
Messages missing from Discord

### ISSUE THREAD

**Issue by DrunkMunki** [LakeYS/7DTD-Discord#100]
The image shows people joining/leaving... but not showing in discord
I have also seen some conversations stop abruptly in discord.. but the text is in the console.

![bbbbbbbbbbbbbb](https://user-images.githubusercontent.com/865746/68456500-0accf700-0252-11ea-8e2d-e2d5e62cf43b.png)

**Comment by LakeYS** [comment]
I'll investigate this soon. This seems to be an issue with the application communicating with Discord since the messages are showing up in the console.

**Comment by LakeYS** [comment]
Should be fixed now! Sorry for the delay.
