### ISSUE TITLE
Using a port other than default results in instant disconnection

### ISSUE THREAD

**Issue by Nashable** [LakeYS/7DTD-Discord#19]
Steps:

1. Set telnet port to 8181
2. use --port parameter and set to 8181
3. Console will show connection then instant disconnect. It will loop.

**Comment by LakeYS** [comment]
I am unable to replicate this, however I did encounter a similar 'loop' issue a few times during development.

Can you find any other conditions that could be related to the issue?

**Comment by Nashable** [comment]
My bad, I double checked and there was a service running on the same box and the port was in use. Not sure if the code could detect that issue and report back an error message?

**Comment by LakeYS** [comment]
No problem at all. I'll look into making the error messages a bit clearer.
