### ISSUE TITLE
Discord messages going to chat when disabled in INI

### ISSUE THREAD

**Issue by doublee313** [LakeYS/7DTD-Discord#66]
I noticed the INI entry to disable ingame chat only turns off incoming messages to Discords, however it still sends messages to the server chat. Can you please disable both? I think it would make more sense with the INI to turn off chat messages. Thanks.

**Comment by LakeYS** [comment]
Yes, I agree that this would probably make more sense. Will look into this soon.

**Comment by LakeYS** [comment]
Resolved in d6c1de7, `disable-chatmsgs` now hides messages from Discord->7DTD and vice versa. This change will show up in the next release.
